openapi: 3.0.0
paths:
  /:
    get:
      operationId: HealthController_check
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Health
  /admin/available-caregivers:
    get:
      operationId: AdminController_getAvailableCaregivers
      parameters:
        - name: start
          required: true
          in: query
          schema:
            type: string
        - name: end
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Admin
  /admin/dashboard:
    get:
      operationId: AdminController_getDashboard
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Admin
  /admin/registrations:
    get:
      operationId: AdminController_getRegistrations
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Admin
  /auth/login:
    post:
      operationId: AuthController_login
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDto'
      responses:
        '201':
          description: ''
      tags:
        - Auth
  /auth/me:
    get:
      operationId: AuthController_me
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Auth
  /auth/register:
    post:
      operationId: AuthController_register
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterDto'
      responses:
        '201':
          description: ''
      tags:
        - Auth
  /caregivers:
    get:
      operationId: CaregiverController_findAll
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Caregiver
  /caregivers/documents:
    post:
      operationId: CaregiverController_uploadDocuments
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - Caregiver
  '/caregivers/documents/{id}':
    delete:
      operationId: CaregiverController_deleteDocument
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Caregiver
  /caregivers/my_documents:
    get:
      operationId: CaregiverController_getDocuments
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Caregiver
  '/caregivers/{caregiverId}':
    get:
      operationId: CaregiverController_caregiverByIdParam
      parameters:
        - name: caregiverId
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Caregiver
    put:
      operationId: CaregiverController_updateCaregiver
      parameters:
        - name: caregiverId
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCaregiverDto'
      responses:
        '200':
          description: ''
      tags:
        - Caregiver
  /patients:
    get:
      operationId: PatientController_findAll
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Patient
    post:
      operationId: PatientController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePatientDto'
      responses:
        '201':
          description: ''
      tags:
        - Patient
  /patients/documents:
    post:
      operationId: PatientController_uploadDocuments
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - Patient
  '/patients/documents/{id}':
    delete:
      operationId: PatientController_deleteDocument
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Patient
  /patients/my_documents:
    get:
      operationId: PatientController_getDocuments
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Patient
  '/patients/{id}':
    get:
      operationId: PatientController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Patient
    patch:
      operationId: PatientController_update
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePatientDto'
      responses:
        '200':
          description: ''
      tags:
        - Patient
  /payments/transfer:
    post:
      operationId: PaymentController_createTransfer
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTransferDto'
      responses:
        '201':
          description: ''
      tags:
        - Payment
  '/payments/{id}':
    get:
      operationId: PaymentController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Payment
  /payrolls:
    get:
      operationId: PayrollsController_findAll
      parameters:
        - name: page
          required: true
          in: query
          schema:
            type: number
        - name: limit
          required: true
          in: query
          schema:
            type: number
        - name: status
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Payrolls
  '/payrolls/caregiver/{id}':
    get:
      operationId: PayrollsController_findAllByCaregiver
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
        - name: page
          required: true
          in: query
          schema:
            type: number
        - name: limit
          required: true
          in: query
          schema:
            type: number
        - name: status
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Payrolls
  /ratings:
    post:
      operationId: RatingsController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRatingDto'
      responses:
        '201':
          description: ''
      tags:
        - Ratings
  '/ratings/{shiftId}':
    get:
      operationId: RatingsController_findByShift
      parameters:
        - name: shiftId
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Ratings
  /shifts:
    get:
      operationId: ShiftsController_findAll
      parameters:
        - name: page
          required: true
          in: query
          schema:
            type: number
        - name: limit
          required: true
          in: query
          schema:
            type: number
        - name: status
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Shifts
    post:
      operationId: ShiftsController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateShiftDto'
      responses:
        '201':
          description: ''
      tags:
        - Shifts
  '/shifts/caregiver/{caregiverProfileId}':
    get:
      operationId: ShiftsController_findByCaregiver
      parameters:
        - name: caregiverProfileId
          required: true
          in: path
          schema:
            type: string
        - name: page
          required: true
          in: query
          schema:
            type: number
        - name: limit
          required: true
          in: query
          schema:
            type: number
      responses:
        '200':
          description: ''
      tags:
        - Shifts
  '/shifts/patient/{patientId}':
    get:
      operationId: ShiftsController_findByPatient
      parameters:
        - name: patientId
          required: true
          in: path
          schema:
            type: string
        - name: page
          required: true
          in: query
          schema:
            type: number
        - name: limit
          required: true
          in: query
          schema:
            type: number
      responses:
        '200':
          description: ''
      tags:
        - Shifts
  '/shifts/patient/{patientId}/next':
    get:
      operationId: ShiftsController_findNext
      parameters:
        - name: patientId
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Shifts
  '/shifts/{id}':
    delete:
      operationId: ShiftsController_remove
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Shifts
    get:
      operationId: ShiftsController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Shifts
    patch:
      operationId: ShiftsController_update
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateShiftDto'
      responses:
        '200':
          description: ''
      tags:
        - Shifts
  '/shifts/{id}/status':
    patch:
      operationId: ShiftsController_updateStatus
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStatusDto'
      responses:
        '200':
          description: ''
      tags:
        - Shifts
info:
  title: Caregiving API
  description: Caregiving PYME API
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    CreatePatientDto:
      type: object
      properties: {}
      example: {}
    CreateRatingDto:
      type: object
      properties: {}
      example: {}
    CreateShiftDto:
      type: object
      properties: {}
      example: {}
    CreateTransferDto:
      type: object
      properties: {}
      example: {}
    LoginDto:
      type: object
      properties: {}
      example: {}
    RegisterDto:
      type: object
      properties: {}
      example: {}
    UpdateCaregiverDto:
      type: object
      properties: {}
      example: {}
    UpdatePatientDto:
      type: object
      properties: {}
      example: {}
    UpdateShiftDto:
      type: object
      properties: {}
      example: {}
    UpdateStatusDto:
      type: object
      properties: {}
      example: {}
